export const AdvisorData = [
  {
    id: 1,
    name: "Gatoya Germaen",
    image: require("../assets/images/instructor1.jpg"),
    facebook: "www.facebook.com",
    twitter: "www.twitter.com",
    youtub: "www.youtub.com",
    instagram: "www.instagram.com",
    whatsup: "0782439775",
  },
  {
    id: 2,
    name: "Gatoya Germaen",
    image: require("../assets/images/instructor3.jpg"),
    facebook: "www.facebook.com",
    twitter: "www.twitter.com",
    youtub: "www.youtub.com",
    instagram: "www.instagram.com",
    whatsup: "0782439775",
  },
  {
    id: 3,
    name: "Gatoya Germaen",
    image: require("../assets/images/instructor2.jpg"),
    facebook: "www.facebook.com",
    twitter: "www.twitter.com",
    youtub: "www.youtub.com",
    instagram: "www.instagram.com",
    whatsup: "0782439775",
  },
  {
    id: 4,
    name: "Gatoya Germaen",
    image: require("../assets/images/instructor1.jpg"),
    facebook: "www.facebook.com",
    twitter: "www.twitter.com",
    youtub: "www.youtub.com",
    instagram: "www.instagram.com",
    whatsup: "0782439775",
  },
  {
    id: 5,
    name: "Gatoya Germaen",
    image: require("../assets/images/instructor3.jpg"),
    facebook: "www.facebook.com",
    twitter: "www.twitter.com",
    youtub: "www.youtub.com",
    instagram: "www.instagram.com",
    whatsup: "0782439775",
  },
  {
    id: 6,
    name: "Gatoya Germaen",
    image: require("../assets/images/instructor1.jpg"),
    facebook: "www.facebook.com",
    twitter: "www.twitter.com",
    youtub: "www.youtub.com",
    instagram: "www.instagram.com",
    whatsup: "0782439775",
  },
  {
    id: 7,
    name: "Gatoya Germaen",
    image: require("../assets/images/instructor3.jpg"),
    facebook: "www.facebook.com",
    twitter: "www.twitter.com",
    youtub: "www.youtub.com",
    instagram: "www.instagram.com",
    whatsup: "0782439775",
  },
  {
    id: 8,
    name: "Gatoya Germaen",
    image: require("../assets/images/instructor1.jpg"),
    facebook: "www.facebook.com",
    twitter: "www.twitter.com",
    youtub: "www.youtub.com",
    instagram: "www.instagram.com",
    whatsup: "0782439775",
  },
  {
    id: 9,
    name: "Gatoya Germaen",
    image: require("../assets/images/instructor2.jpg"),
    facebook: "www.facebook.com",
    twitter: "www.twitter.com",
    youtub: "www.youtub.com",
    instagram: "www.instagram.com",
    whatsup: "0782439775",
  },
];
